name: Add

on:
  workflow_dispatch:
    inputs:
      Name:
        description: 'Name'
        required: true
        type: string
      URL:
        description: 'URL to the repository'
        required: true 
        type: string
      Description:
        description: 'Description'
        required: true
        type: string
      Tags:
        description: 'Tags (separated by commas)'
        required: true
        type: string

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install
      run: go install ./cmd/uslibs

    - name: Add
      run: uslibs add --name "${{ github.event.inputs.Name }}" \
        --url "${{ github.event.inputs.URL }}" \
        --description "${{ github.event.inputs.Description }}" \
        --tags "${{ github.event.inputs.Tags }}"

    - name: Update
      run: uslibs list --markdown > README.md

    - name: Commit and Push
      run: |
        git config --global user.email "55233766+lemon-mint@users.noreply.github.com"
        git config --global user.name "lemon-mint"
        git add .
        git commit -m "Auto Update `date`"
        git push 

