name: Del

on:
  workflow_dispatch:
    inputs:
      ID:
        description: 'ID to delete'
        required: true
        type: integer

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install
      run: go install ./cmd/uslibs

    - name: Del
      run: uslibs del --id "${{ github.event.inputs.ID }}"

    - name: Update
      run: uslibs list --markdown > README.md

    - name: Commit and Push
      run: |
        git config --global user.email "55233766+lemon-mint@users.noreply.github.com"
        git config --global user.name "lemon-mint"
        git add .
        git commit -m "Auto Update `date`"
        git push 

